# Generated by Django 3.2.5 on 2021-07-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_auto_20210720_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='news',
        ),
        migrations.AddField(
            model_name='news',
            name='comments',
            field=models.ManyToManyField(to='app_news.Comment'),
        ),
    ]
