# Generated by Django 3.2.5 on 2021-07-17 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0004_auto_20210717_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_advertisements', to='app_advertisements.advertisementstatus'),
        ),
    ]
