# Generated by Django 3.2.5 on 2021-07-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0005_alter_advertisement_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='app_advertisements',
        ),
    ]
