# Generated by Django 3.2.5 on 2021-07-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0006_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['title']},
        ),
    ]
