# Generated by Django 3.2.5 on 2021-07-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0010_auto_20210719_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(default='mail@mail.com', max_length=30, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='Unnamed', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='telephone',
            field=models.CharField(max_length=11, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='rubric',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_advertisements.rubric'),
        ),
    ]
