# Generated by Django 3.2.5 on 2021-07-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0011_auto_20210719_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='name',
            field=models.CharField(default='No rubric', max_length=50, verbose_name='Рубрика'),
        ),
    ]
